### ISSUE TITLE
Add axes, indicator, media controls, info card to verification grid (adopt common templated elements)

### ISSUE THREAD

**Issue by hudson-newey** [ecoacoustics/web-components#115]
Some users have expressed the desire to add/remove info-cards, axes elements, etc... after the verification grid has been created.

Instead of requiring the user to add a html template element to modify how each verification grid tile looks, we should have a default template that the user can customize through the user interface.

We might consider adding this to a global settings component

**Comment by atruskie** [comment]
>[Yesterday 18:59] Anthony Truskinger
>I'm starting to think we should stop using a template for the verification grid. 
 
>We might still have a template so a user can add some custom content - in other words, reduce the scope of the template.
 
>So spectrogram, axes, media controls all become non templated.
 
>But you could still template the information pane for example 
 
>[Yesterday 19:00] Anthony Truskinger
This would solve some of our event interaction issues too
