### ISSUE TITLE
Improve semantic meaning of a decision button with a highlight color

### ISSUE THREAD

**Issue by hudson-newey** [ecoacoustics/web-components#122]
At the moment, all decision buttons that are used on the viewable page are highlighted.

However, we have had multiple users express that the current behavior of the decision button highlights is confusing and not immediately understandable.

Users have expected that when sub-selecting, only the decision(s) applied to the selected tile would be highlighted.

We will have to discuss what the best solution to this problem.

**Comment by atruskie** [comment]
I suspect we'll need a few goes to get this right, but yes let's change it so that when a selection is made, only the decision buttons involved are highlighted.

No selection is equivalent to select all which equivalent to the current behavior.

See also the meter issue:
