### ISSUE TITLE
Prompt users to enter the browsers "fullscreen" mode

### ISSUE THREAD

**Issue by hudson-newey** [ecoacoustics/web-components#130]
Many end users use a small screen size, and therefore cannot see a large portion of the verification grid.

We should add a prompt for users to enter full screen mode for the best experience, and provide them with a button to enter/exit full screen mode.

Additional note:

- The browser should leave full screen mode when the tab is closed and should return to full screen when the tab is re-focused

**Comment by atruskie** [comment]
Probably should have a full screen button somewhere
