### ISSUE TITLE
Tiles should show completed and required actions as a meter with discrete ordered segments

### ISSUE THREAD

**Issue by hudson-newey** [ecoacoustics/web-components#134]
Classification/verification tasks currently use a multi-segmented border to show what decisions have been applied to a tile.

However, this does not convey to the users how far through the classification task they are.

We should instead use a segmented "completion bar" which uses empty space to say that a task has not been completed.

e.g. a number of actions have to be completed for each task. So for a verification and 2 class task, we have a 3 segment meter:

```
<verifciation-status> | <class-1-status> | <class-2-status>
```

So each tile would start off in an neutral state:

```
background-color | background-color | background-color
```

And if a `class-2` `positive` decision is applied:

```
background-color | background-color | class-2-color-positive
```

And when all required actions are completed the meter will have all segments lit:

```
verification-positive-color | class-1-negative-color | class-2-positive
```

**Comment by atruskie** [comment]
The meter could show the class/tag labels in the bar as well. This would work for _stakeholder-d_. We'll trial how this looks though I'm not convinced it will look good.
