### ISSUE TITLE
Remove positive classifications (optional classifications)

### ISSUE THREAD

**Issue by hudson-newey** [ecoacoustics/web-components#135]
At the moment, it is possible to have positive only classifications in a verification grid.

However, this can lead to unexpected behaviors such as the toggling of decisions and auto paging (as we don't know when the user has completed all decisions)

By requiring users to make a "positive", "negative", "skip", or "unsure" decision about every tag, we can resolve many issues.

**Comment by atruskie** [comment]
Yeah so, another way to phrase this is _optional_ and _mandatory_ classifications.

If we only every have mandatory classifications, i.e. a user must move away from the neutral state to complete a decision, then we can avoid a bunch of problems.
