### ISSUE TITLE
Progress bar to indicate verification progress and page

### ISSUE THREAD

**Issue by nellihol** [ecoacoustics/web-components#163]
Progress Bar to indicate where user is relatively to the number of verification tasks. 

Two functions:
1) Show progress
2) act as a navigation between the verification tiles

Style inspiration (Source [Material kit 3](https://www.figma.com/community/file/1035203688168086460)):
![image](https://github.com/user-attachments/assets/20be3a65-cf4a-404b-a18b-736cf56e7ed8)

**Comment by atruskie** [comment]
Associated with #114
