### ISSUE TITLE
Exit Fullscreen Icon Missing

### ISSUE THREAD

**Issue by nellihol** [ecoacoustics/web-components#171]
## Describe the bug

Full screen mode icon disappears when in full screen mode. There should be an icon indicating exit full screen mode.

## To Reproduce

1. Go to 'Multiple Verification Grid'
2. Click on 'Full Screen' button
4. See error: No Exit Full Screen icon on the button

## Expected behavior
Expecting an icon similar to this:
![1126](https://github.com/user-attachments/assets/c431b8bc-030d-49ea-a667-f49142685058)
(Arrows pointing to middle)

## Screenshots

![image](https://github.com/user-attachments/assets/e443782e-080b-462c-b4bd-6ba825a73430)

**Comment by hudson-newey** [comment]
Fixed in https://github.com/ecoacoustics/web-components/pull/161
