### ISSUE TITLE
Using unexepected primitive type in dataset causes sub-selection feedback to break for verification only tasks

### ISSUE THREAD

**Issue by hudson-newey** [ecoacoustics/web-components#213]
We have previously assumed that the tags the subject model would provide is an object or string.

However, if the user inputs a primitive type that is not an object (with the correct keys) or a string (e.g. array, symbol, etc...), the sub-selection will break if it is a verification-only task.

Although verification only tasks typically require a tag to be present on each model, we should either

- hard fail; disabling the verification grid and displaying an error that "tag" is required for a verification only task
- Or retain the functionality of the verification grid

The current behavior of only breaking sub-selection feedback is not the expected behavior here (especially since decisions are still applied, but the feedback is not given).

---

I recommend that if the user creates a verification grid with verification tasks, we should still allow the user to make decisions

**Comment by atruskie** [comment]
yup we should emit a console warning and .toString whatever was input
